# Generated by Django 3.0.7 on 2020-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(auto_created=True, verbose_name='Fecha'),
        ),
    ]
