# Generated by Django 3.0.7 on 2020-06-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='comentario',
        ),
        migrations.AddField(
            model_name='orden',
            name='comentario',
            field=models.CharField(default='', max_length=255, verbose_name='Comentarios'),
        ),
    ]
