# Generated by Django 3.0.7 on 2020-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200613_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
