# Generated by Django 3.0.7 on 2020-06-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_menu_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='schedule',
            field=models.DateField(blank=True),
        ),
    ]
