# Generated by Django 3.0.7 on 2020-06-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200615_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='timestamp',
        ),
    ]
