# Generated by Django 3.0.7 on 2020-06-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200613_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='plato',
        ),
        migrations.AddField(
            model_name='menu',
            name='opciones',
            field=models.ManyToManyField(to='my_app.Plato', verbose_name='Plato'),
        ),
    ]
